# Health check endpoint (Should return HTTP 200)
GET http://localhost:8080/health

###
GET https://gitlab.stud.idi.ntnu.no/api/v4/projects/15903/repository/commits?all=true&per_page=2000&with_stats=true
PRIVATE-TOKEN: {{gitlabAccessToken}}

###
GET https://gitlab.stud.idi.ntnu.no/api/v4/projects/15903/repository/commits/a48421190165bb83dd515b2b24445328cb41317a
PRIVATE-TOKEN: {{gitlabAccessToken}}

###
# Get group details
GET https://gitlab.stud.idi.ntnu.no/api/v4/groups/it3920-gitlab-projects-examples
PRIVATE-TOKEN: {{gitlabAccessToken}}

###
# List subgroups
GET https://gitlab.stud.idi.ntnu.no/api/v4/groups/it3920-gitlab-projects-examples/subgroups
PRIVATE-TOKEN: {{gitlabAccessToken}}

###
# List projects in group
GET https://gitlab.stud.idi.ntnu.no/api/v4/groups/it3920-gitlab-projects-examples%2Fgroup2022001/projects/
PRIVATE-TOKEN: {{gitlabAccessToken}}

###
GET https://gitlab.stud.idi.ntnu.no/api/v4/projects/1021/merge_requests/?per_page=2000
PRIVATE-TOKEN: {{gitlabAccessToken}}

###
GET https://gitlab.stud.idi.ntnu.no/api/v4/projects/1021/issues/4
PRIVATE-TOKEN: {{gitlabAccessToken}}

###
GET https://gitlab.stud.idi.ntnu.no/api/v4/projects/15903/repository/files/.gitignore?ref=master
PRIVATE-TOKEN: {{gitlabAccessToken}}

###
GET https://gitlab.stud.idi.ntnu.no/api/v4/projects/15903/repository/tree?recursive=true&per_page=100&page=1
PRIVATE-TOKEN: {{gitlabAccessToken}}

###
GET https://gitlab.stud.idi.ntnu.no/api/v4/projects/16111/issues?per_page=100&page=1
PRIVATE-TOKEN: {{gitlabAccessToken}}
###
GET https://gitlab.stud.idi.ntnu.no/api/v4/projects/1021/issues/29/notes?per_page=100&page=1
PRIVATE-TOKEN: {{gitlabAccessToken}}
