
services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: gitlabstats
      POSTGRES_PASSWORD: somepassword
      POSTGRES_DB: gitlabstats
      POSTGRES_HOST_AUTH_METHOD: trust
  app:
    build:
      context: .
      # This Dockerfile is more tailored for local development and continuous
      # recompilation. Use docker compose restart app to trigger a rebuild
      dockerfile: docker/Dockerfile
    command: ./docker/run_dev.sh
    ports:
      - "8080:8080"
    volumes:
      - .:/app/
    depends_on:
      - db
      - rabbitmq
    env_file:
      - secrets.env
    environment:
      DATABASE_USER: gitlabstats
      DATABASE_PASSWORD: somepassword
      DATABASE_URI: jdbc:postgresql://db:5432/gitlabstats?stringtype=unspecified
      RABBITMQ_USER: 'user'
      RABBITMQ_PASSWORD: 'somePassword'
      RABBITMQ_HOST: 'amqp://rabbitmq'
      COURSE_ROOT_GROUP_PATH: 'it3920-gitlab-projects-examples'
  rabbitmq:
    image: rabbitmq:3
    environment:
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'somePassword'

volumes:
  grafana-storage:
