micronaut:
  application:
    name: gitlabstatscrawler
  server:
    port: 8080
    cors: false

  http:
    client:
      max-content-length: 104857600 # 100mb max content length
      read-timeout: 60s

    services:
      gitlabapi:
        urls:
          - "https://gitlab.stud.idi.ntnu.no"
        exception-on-error-status: true

  security:
    enabled: false

endpoints:
  # All endpoints should explicitly be disabled
  all:
    enabled: false
  health:
    enabled: true
    sensitive: false
#  prometheus:
#    enabled: true
#    sensitive: true

netty:
  default:
    allocator:
      max-order: 3

jackson:
  serialization:
    indentOutput: true
    writeDatesAsTimestamps: false
  deserialization:
    useBigIntegerForInts: true
    # It is recommended to simply ignore properties in a JSON structure
    # that our data class / structure haven't declared, because it decouples
    # the JSON-schema from the application. We can later add new properties, or remove unused ones without
    # resulting in cascading failures to consuming applications.
    failOnUnknownProperties: false
    # ALWAYS use UTC
    adjustDatesToContextTimeZone: false
  json-view:
    enabled: true

datasources:
  default:
    driverClassName: 'org.postgresql.Driver'
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URI}

flyway:
  datasources:
    default:
      # Disabled until we actually have any tables in resources/db/migration/
      enabled: false

gitlabapi:
  accessToken: ${GITLAB_ACCESS_TOKEN}
